version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: testdb
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_ENDPOINT: mongodb://admin:root@mongodb:27017/testdb?authSource=admin
    ports:
      - 8080:8080
    depends_on:
      - mongodb